"""accounts, account types and value snapshots

Revision ID: 6138b58d8b03
Revises: 
Create Date: 2026-06-27 14:45:46.478418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6138b58d8b03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('classification', sa.Enum('asset', 'liability', name='classification'), nullable=False),
    sa.Column('tracks_loan', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('value_cents', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_value_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_value_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_value_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_account_value_account_id'))

    op.drop_table('account_value')
    op.drop_table('account')
    op.drop_table('account_type')
    # ### end Alembic commands ###
