"""account value loan balance

Revision ID: cb4094e6382d
Revises: d31280998cfd
Create Date: 2026-06-27 18:24:41.939788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4094e6382d'
down_revision = 'd31280998cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_cents', sa.Integer(), nullable=True))
        batch_op.create_check_constraint(
            'ck_account_value_loan_nonneg',
            'loan_cents IS NULL OR loan_cents >= 0',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_value', schema=None) as batch_op:
        batch_op.drop_constraint('ck_account_value_loan_nonneg', type_='check')
        batch_op.drop_column('loan_cents')

    # ### end Alembic commands ###
