"""cashflow entries

Revision ID: d31280998cfd
Revises: 6138b58d8b03
Create Date: 2026-06-27 17:32:04.570340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31280998cfd'
down_revision = '6138b58d8b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflow_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('income', 'expense', name='cashflowkind'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount_cents >= 0', name='ck_cashflow_amount_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashflow_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashflow_entry_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashflow_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashflow_entry_kind'))

    op.drop_table('cashflow_entry')
    # ### end Alembic commands ###
